<?php namespace ProcessWire;

class DashboardPanelShortcuts extends DashboardPanel {

    public static function getModuleInfo() {
        return array_merge(parent::getModuleInfo(),
            [
                'title'    => __('Dashboard Panel: Shortcuts', __FILE__),
                'summary'  => __('Display a list of shortcuts to admin pages', __FILE__),
                'author'   => 'Philipp Daun',
                'version'  => DASHBOARD_VERSION,
            ]
        );
    }

    public function getIcon() {
        return 'flash';
    }

    public function getTitle() {
        return $this->_('Shortcuts');
    }

    public function getContent() {
        if (!($this->shortcuts && count($this->shortcuts))) {
            return;
        }

        $rows = array_map(function ($shortcut, $key) {
            if (is_object($shortcut) && $shortcut instanceof Page) {
                $page = $shortcut;
            } else if (is_int($shortcut)) {
                $page = $this->pages->get($shortcut);
            } else if (is_string($shortcut)) {
                $page = $this->pages->get($shortcut);
            }

            if (!$page) {
                return;
            }

            $title = is_string($key) ? $key : $page->title;
            $url = $page->url;
            $icon = $this->renderPageIcon($page);

            return "<li><a href='{$url}'>{$icon} {$title}</a></li>";
        }, $this->shortcuts, array_keys($this->shortcuts));

        $output = join('', $rows);
        return "<ul>{$output}</ul>";
    }

    protected function renderPageIcon($page) {
        if ($this->icon === null) {
            $icon = $page->getIcon() ?: $this->fallbackIcon;
        } else if ($this->icon) {
            $icon = $this->icon;
        }
        return $icon ? wireIconMarkup($icon, 'fw') : '';
    }

    public function setup() {
        parent::setup();
        $this->shortcuts = $this->data['shortcuts'] ?? [];
        $this->fallbackIcon = $this->data['fallbackIcon'] ?? 'bookmark-o';
        $this->icon = $this->data['icon'] ?? null;
    }
}
