<?php namespace ProcessWire;

class DashboardPanelShortcuts extends DashboardPanel {

    public static function getModuleInfo() {
        return array_merge(parent::getModuleInfo(),
            [
                'title'    => __('Dashboard Panel: Shortcuts', __FILE__),
                'summary'  => __('Display a list of shortcuts to admin pages', __FILE__),
                'author'   => 'Philipp Daun',
                'version'  => DASHBOARD_VERSION,
            ]
        );
    }

    const displayOptions = [
        'grid',
        'list',
    ];

    const defaultDisplayOption = 'grid';

    public function getIcon() {
        return 'flash';
    }

    public function getTitle() {
        return $this->_('Shortcuts');
    }

    public function getContent() {
        if (!($this->shortcuts && count($this->shortcuts))) {
            return;
        }

        $rows = array_map(function ($shortcut, $key) {
            $page = null;
            $url = '';
            $icon = '';

            if (is_array($shortcut)) {
                list($shortcut, $icon) = $shortcut;
            }

            if (is_object($shortcut) && $shortcut instanceof Page) {
                $page = $shortcut;
            } else if (is_int($shortcut)) {
                $page = $this->pages->get($shortcut);
            } else if (is_string($shortcut)) {
                if (Selectors::stringHasSelector($shortcut)) {
                    $page = $this->pages->get($shortcut);
                } else {
                    $url = $shortcut;
                }
            }

            if ($page) {
                $title = is_string($key) ? $key : $page->title;
                $url = $page->url;
            } else if ($url) {
                $title = $key;
            } else {
                return;
            }
            $icon = $icon ? $this->renderIcon($icon) : $this->renderPageIcon($page);

            return "<li><a href='{$url}'>{$icon} {$title}</a></li>";
        }, $this->shortcuts, array_keys($this->shortcuts));

        $output = join('', $rows);
        return "<ul data-display='{$this->display}'>{$output}</ul>";
    }

    protected function renderPageIcon($page = null) {
        if ($this->icon !== null) {
            $icon = $this->icon;
        } elseif ($page) {
            $icon = $page->getIcon() ?: $this->fallbackIcon;
        } else {
            $icon = $this->fallbackIcon;
        }

        return $icon ? wireIconMarkup($icon, 'fw') : '';
    }

    public function setup() {
        parent::setup();
        $this->shortcuts = $this->data['shortcuts'] ?? [];
        $this->display = $this->sanitizer->option($this->data['display'] ?? '', self::displayOptions) ?: self::defaultDisplayOption;
        $this->fallbackIcon = $this->data['fallbackIcon'] ?? 'bookmark-o';
        $this->icon = $this->data['icon'] ?? null;
    }
}
