<?php namespace ProcessWire;

class DashboardPanelPageList extends DashboardPanel {

    public static function getModuleInfo() {
        return array_merge(parent::getModuleInfo(),
            [
                'title'    => __('Dashboard Panel: PageList', __FILE__),
                'summary'  => __('Display a ProcessPageList widget for any parent', __FILE__),
                'author'   => 'Philipp Daun',
                'version'  => DASHBOARD_VERSION,
            ]
        );
    }

    public function getContent() {
        $module = $this->modules->get('ProcessPageList');
        $module->set('id', $this->parentID);
        $module->set('showRootPage', $this->showRootPage);
        return $module->execute();
    }

    public function setup() {
        parent::setup();
        $this->parent = $this->getPageFromObjectOrSelectorOrID($this->data['parent'] ?? null);
        $this->parentID = $this->parent ? $this->parent->id : null;
        $this->showRootPage = $this->data['showRootPage'] ?? true;
    }
}
